### ISSUE TITLE
draw_ego_hub: IndexError: string index out of range

### ISSUE THREAD

**Issue by mlliarm** [mlliarm/the_road_network_of_crete#2]
Traceback:

```
Traceback (most recent call last):
  File "model_cretan_road_network.py", line 363, in <module>
    main()
  File "model_cretan_road_network.py", line 316, in main
    draw_ego_hub(G, "crete_")
  File "model_cretan_road_network.py", line 114, in draw_ego_hub
    (largest_hub, degree) = sorted(node_and_degree, key=itemgetter(1))[-1]
IndexError: string index out of range
```

**Comment by mlliarm** [comment]
Seems to be working now, automagically. Possibly a transient issue.

Closing bug.
