### ISSUE TITLE
draw_network: AttributeError: module 'matplotlib.pyplot' has no attribute 'ishold'

### ISSUE THREAD

**Issue by mlliarm** [mlliarm/the_road_network_of_crete#4]
```
Traceback (most recent call last):
  File "model_cretan_road_network.py", line 395, in <module>
    main()
  File "model_cretan_road_network.py", line 353, in main
    draw_network(erdos_renyi_G1, "erdos_renyi_0.1_","circular")
  File "model_cretan_road_network.py", line 94, in draw_network
    nx.draw_circular(G, with_labels = True)
  File "/usr/lib/python3/dist-packages/networkx/drawing/nx_pylab.py", line 900, in draw_circular
    draw(G, circular_layout(G), **kwargs)
  File "/usr/lib/python3/dist-packages/networkx/drawing/nx_pylab.py", line 126, in draw
    b = plt.ishold()
AttributeError: module 'matplotlib.pyplot' has no attribute 'ishold'
```
To reproduce run main script with any parameter (eg. circular):

`python3 model_cretan_road_network.py circular`

**Comment by mlliarm** [comment]
Bug automagically fixed, now that I check it.

Possibly a recurrent bug of the `matplotlib` package?

Uncommenting the related line in `main` method and running the script, it doesn't produce the aforementioned error now.

**Comment by mlliarm** [comment]
See commit  25d39c7.

Closing bug.
